name: Check Maven
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'isyfact-standards-doc'
  push:
    branches:
      - master
    paths-ignore:
      - 'isyfact-standards-doc'

jobs:
  Maven:
    uses: IsyFact/isyfact-standards/.github/workflows/maven_template.yml@master
    with:
      version: '3.0.0-SNAPSHOT'
