name: Check Maven
on:
  pull_request:
    branches:
      - master
      - 'release/**'
    paths-ignore:
      - 'isyfact-standards-doc'
  push:
    branches:
      - master
      - 'release/**'
    paths-ignore:
      - 'isyfact-standards-doc'

jobs:
  Maven:
    uses: IsyFact/isyfact-standards/.github/workflows/maven_build_template.yml@master
    with:
      version: '3.0.0-SNAPSHOT'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}