name: Next Version Template
on:
  workflow_call:
    inputs:
      branch-name:
        description: 'The branch for which the version is being prepared'
        type: string
        required: true
      base-version:
        description: 'Base version to use, e.g., 4.0.0'
        type: string
        required: false
      calculate-rc:
        description: 'Whether to calculate a release candidate version'
        type: boolean
        required: false
        default: false
    outputs:
      next-version:
        description: 'Calculated version with appropriate suffix'
        value: ${{ jobs.Next.outputs.next-version }}

jobs:
  Next:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: none
      checks: none
      deployments: none
      issues: none
      packages: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none

    outputs:
      next-version: ${{ steps.calculate-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Fetch develop branch
        run: git fetch origin develop:develop
      - name: Calculate semantic version
        id: semantic-version
        if: ${{ ! inputs.base-version }}
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          version_from_branch: true
          tag_prefix: ""
          major_pattern: "/BREAKING/"
          minor_pattern: "/feat/"
          search_commit_body: true
      - name: Validate version
        if: ${{ ! inputs.base-version }}
        run: |
          RE_SEMVER="^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$"
          if [[ ! "${{ steps.semantic-version.outputs.version }}" =~ $RE_SEMVER ]]; then
            echo "ERROR calculated version with value ${{ steps.semantic-version.outputs.version }} is an invalid semantic version"
              exit 1
          fi

      - name: Calculate next version
        id: calculate-version
        run: |
          BASE_VERSION="${{ inputs.base-version }}"
          BRANCH_NAME="${{ inputs.branch-name }}"
          CALCULATE_RC="${{ inputs.calculate-rc }}"
          
          # Use the semantic version or a provided base version, defaulting to the semantic version output if base-version is empty
          FINAL_BASE_VERSION="${BASE_VERSION:-${{ steps.semantic-version.outputs.version }}}"
          
          if [[ "$CALCULATE_RC" == 'true' && "$BRANCH_NAME" =~ ^feature/ ]]; then
            # Calculate the number of commits on this release branch since its creation from develop
            BASE_BRANCH='develop'
            COMMON_ANCESTOR=$(git merge-base HEAD refs/heads/$BASE_BRANCH)
            COMMIT_COUNT=$(git rev-list --count $COMMON_ANCESTOR..HEAD)
            NEXT_VERSION="${FINAL_BASE_VERSION}-RC-${COMMIT_COUNT}"
          else
            # Standard snapshot versioning for non-release branches
            NEXT_VERSION="${FINAL_BASE_VERSION}-SNAPSHOT"
          fi
          
          echo "version=$NEXT_VERSION" >> $GITHUB_OUTPUT
          echo "Calculated version: $NEXT_VERSION"